# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a35ebedbd88238297f6bd11b2922036d76e57f73e2beb285b7f8d1f6018529df0e19c337976dc3500d79975c00e5895a36dd3089322e6d24d26f1a22a26df3f

test:
  secret_key_base: 63353795b5fba68ee2506d31fc07601c845421938816e82972088312185097efdd5eb867af4bd3ff82097e2b4d2946bad0f3ca9bea3c7e5e561d7e694d1f96b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
